site_name: Documentation for Paladinleeds
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: darkblue
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: darkblue
      accent: pink

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/paladinleeds]
    - icon: fontawesome/brands/threads
      link: https://threads.com/@paladinleeds
    - icon: fontawesome/brands/discord
      link: https://discord.gg/tmnv48e

markdown_extensions: 
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite:
  - pymdownx.snippets:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://www.github.com/paladinleeds/" target="_blank">Paladinleeds</a>