site_name: Paladinleeds - Plugin & Addon Documentation
site_url: https://paladinleeds.github.io/
theme:
  logo: assets/PaladinLeedsSmall.png
  favicon: assets/PaladinLeedsSmall.png
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.index
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: darkblue
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: darkblue
      accent: pink

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/paladinleeds
      name: GitHub
    - icon: fontawesome/brands/threads
      link: https://threads.net/@paladinleeds
      name: Threads
    - icon: fontawesome/brands/discord
      link: https://discord.gg/tmnv48e
      name: Discord
    - icon: fontawesome/solid/person-half-dress
      link: https://en.pronouns.page/@paladinleeds
      name: Pronouns.page
  consent:
    title: Only the most heavenly of cookies. But we don't give them out without permission.
    description: >-
      Please note that we use cookies to recognise your repeated visits and preferences. We also use this to measure the effectiveness of our documentation. We want to make sure that you find what you are looking for. You can update your consent at any time by clicking the link at the bottom of the page.
    actions:
      - accept
      - reject
      - manage
    cookies:
      analytics:
        name: Google Analytics
        checked: false
      github:
        name: GitHub
        checked: false

plugins:
  - privacy

markdown_extensions: 
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite:
  - pymdownx.snippets:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
      title: Here you'll find...

copyright: |
  &copy; 2024 <a href="https://www.github.com/paladinleeds/" target="_blank">Paladinleeds</a> - <a href="#__consent">Manage your cookie consent</a>